
/*
 * Oceanengine Open Api
 * 巨量引擎开放平台 Open Api
 *
 * The version of the OpenAPI document: 1.1.71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bytedance.ads.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
 * 直播全域一键起量探索目标或直播全域-素材追投-控成本投放-优化目标
 */
@JsonAdapter(QianchuanUniPromotionAdControlTaskListV10ExternalAction.Adapter.class)
public enum QianchuanUniPromotionAdControlTaskListV10ExternalAction {

    AD_CONVERT_TYPE_LIVE_PAY_ROI("AD_CONVERT_TYPE_LIVE_PAY_ROI"),

    AD_CONVERT_TYPE_LIVE_SUCCESSORDER_PAY("AD_CONVERT_TYPE_LIVE_SUCCESSORDER_PAY");

    private String value;

    QianchuanUniPromotionAdControlTaskListV10ExternalAction(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    public static QianchuanUniPromotionAdControlTaskListV10ExternalAction fromValue(String value) {
        for (QianchuanUniPromotionAdControlTaskListV10ExternalAction b : QianchuanUniPromotionAdControlTaskListV10ExternalAction.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<QianchuanUniPromotionAdControlTaskListV10ExternalAction> {
        @Override
        public void write(final JsonWriter jsonWriter, final QianchuanUniPromotionAdControlTaskListV10ExternalAction enumeration) throws IOException {
            jsonWriter.value(enumeration.getValue());
        }

        @Override
        public QianchuanUniPromotionAdControlTaskListV10ExternalAction read(final JsonReader jsonReader) throws IOException {
            String value = jsonReader.nextString();
            return QianchuanUniPromotionAdControlTaskListV10ExternalAction.fromValue(value);
        }
    }
}