/*
 * Oceanengine Open Api
 * 巨量引擎开放平台 Open Api
 *
 * The version of the OpenAPI document: 1.1.71
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bytedance.ads.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
 * 直播全域素材追投方式
 */
@JsonAdapter(QianchuanUniPromotionAdControlTaskListV10SmartBidType.Adapter.class)
public enum QianchuanUniPromotionAdControlTaskListV10SmartBidType {

    SMART_BID_CONSERVATIVE("SMART_BID_CONSERVATIVE"),

    SMART_BID_CUSTOM("SMART_BID_CUSTOM");

    private String value;

    QianchuanUniPromotionAdControlTaskListV10SmartBidType(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    public static QianchuanUniPromotionAdControlTaskListV10SmartBidType fromValue(String value) {
        for (QianchuanUniPromotionAdControlTaskListV10SmartBidType b : QianchuanUniPromotionAdControlTaskListV10SmartBidType.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<QianchuanUniPromotionAdControlTaskListV10SmartBidType> {
        @Override
        public void write(final JsonWriter jsonWriter, final QianchuanUniPromotionAdControlTaskListV10SmartBidType enumeration) throws IOException {
            jsonWriter.value(enumeration.getValue());
        }

        @Override
        public QianchuanUniPromotionAdControlTaskListV10SmartBidType read(final JsonReader jsonReader) throws IOException {
            String value = jsonReader.nextString();
            return QianchuanUniPromotionAdControlTaskListV10SmartBidType.fromValue(value);
        }
    }
}
